import Navbar from "@/components/navbar/Navbar";

 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashLayout({ children }) {
  return (
    <html lang="en">
    <body>
         <div>
            <Navbar />
         </div>
         <div>
         {children}
         </div>
        
    </body>
    </html>
  );
}